package com.anastasko.lnucompass.model.enums;

public enum EntityTypeName {

    CITY_ITEM, MAP,
    USER_ACCOUNT, SOCIAL_USER_ACCOUNT, MAP_ITEM, 
    CITY_ITEM_KIND, ITEM_KIND, ITEM_KIND_ICON, ROOT, ICON, IOS_ICON, ANDROID_ICON, UNDEFINED, FACULTY, URL_RESOURCE

}
